'use client'

import ComingSoon from '@/components/ui/ComingSoon'
import { useParams } from 'next/navigation'

export default function DynamicReportPage() {
    const params = useParams()
    const slug = params.slug as string

    // Convert slug to title case (e.g., "same-store-sales" -> "Same Store Sales")
    const title = slug
        .split('-')
        .map(word => word.charAt(0).toUpperCase() + word.slice(1))
        .join(' ') + ' Report'

    return <ComingSoon title={title} description="This detailed report is being generated by our analytics engine and will be available soon." />
}
